"""Working Data table: build, sort, render, export, re-parse.

ARCHITECTURE.md section 5:

* ``working_data_YYYY-MM-DD.md``   -- the exact documented column table, sorted by
  ``confidence`` desc then ``datePublished`` desc.
* ``working_data_YYYY-MM-DD.json`` -- a compact array of objects matching the
  section 4 schema, "generated by parsing the markdown table (see export_json.py
  logic)".  :func:`parse_markdown_table` is that logic, and
  :func:`export_json_from_markdown` is the section-5 path; :func:`export_json`
  exists for callers that already hold rows.

Every file open in this module passes ``encoding="utf-8"`` explicitly -- this box's
locale default is cp1252 and would mangle Japanese kit names on write and blow up
on read.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Iterable, Optional, Sequence

from .models import (
    EMPTY_CELL,
    WORKING_DATA_COLUMNS,
    WORKING_DATA_FIELDS,
    WORKING_DATA_JSON_KEYS,
    WorkingDataRow,
)
from .verification import CONFIDENCE_RANK

#: Cell values that decode back to a boolean ``image_checked``.
_TRUE_CELLS = {"true", "yes", "1"}
_BOOL_FIELDS = {"image_checked"}


# ---------------------------------------------------------------------------
# Sorting
# ---------------------------------------------------------------------------


def sort_rows(rows: Iterable[WorkingDataRow]) -> list:
    """Sort by ``confidence`` desc, then ``datePublished`` desc (section 5).

    ``date_published`` is compared as a plain string; ISO-8601 / ``YYYY-MM-DD``
    dates sort correctly lexicographically, and a missing date sorts last because
    "" is less than any real date under a descending sort.
    """
    return sorted(
        rows,
        key=lambda r: (
            CONFIDENCE_RANK.get(r.confidence, -1),
            r.date_published or "",
        ),
        reverse=True,
    )


# ---------------------------------------------------------------------------
# Markdown table
# ---------------------------------------------------------------------------


def _escape_cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def render_markdown_table(rows: Sequence[WorkingDataRow], *, sort: bool = True) -> str:
    """Render the documented column table (header + separator + one row each)."""
    ordered = sort_rows(rows) if sort else list(rows)
    lines = [
        "| " + " | ".join(WORKING_DATA_COLUMNS) + " |",
        "| " + " | ".join("---" for _ in WORKING_DATA_COLUMNS) + " |",
    ]
    for row in ordered:
        lines.append("| " + " | ".join(_escape_cell(c) for c in row.to_cells()) + " |")
    return "\n".join(lines) + "\n"


#: Split on UNESCAPED pipes only. A naive ``line.split("|")`` turns one cell
#: containing an escaped pipe into two cells, and the row then fails the
#: column-count check for a reason that has nothing to do with the schema.
_UNESCAPED_PIPE = re.compile(r"(?<!\\)\|")


def _split_row(line: str) -> list:
    inner = line.strip()
    if inner.startswith("|"):
        inner = inner[1:]
    if inner.endswith("|") and not inner.endswith("\\|"):
        inner = inner[:-1]
    return [c.replace("\\|", "|").strip() for c in _UNESCAPED_PIPE.split(inner)]


def _is_separator(cells: Sequence[str]) -> bool:
    return bool(cells) and all(set(c) <= set("-: ") and "-" in c for c in cells)


def parse_markdown_table(markdown: str) -> list:
    """Parse a rendered Working Data table back into section-4 JSON objects.

    This is the ``export_json.py`` logic ARCHITECTURE.md section 5 refers to: the
    JSON export is derived from the markdown table, so the two files cannot drift.
    Raises ``ValueError`` if the header does not match the documented columns --
    a silently-accepted wrong header is how column drift ships unnoticed.
    """
    header_cells: Optional[list] = None
    records: list = []

    for raw in markdown.splitlines():
        line = raw.strip()
        if not line.startswith("|"):
            continue
        cells = _split_row(line)
        if header_cells is None:
            header_cells = cells
            if tuple(header_cells) != WORKING_DATA_COLUMNS:
                raise ValueError(
                    "working data header mismatch:\n  got      %r\n  expected %r"
                    % (tuple(header_cells), WORKING_DATA_COLUMNS)
                )
            continue
        if _is_separator(cells):
            continue
        if len(cells) != len(WORKING_DATA_COLUMNS):
            raise ValueError(
                "row has %d cells, expected %d: %r"
                % (len(cells), len(WORKING_DATA_COLUMNS), line)
            )
        record: dict = {}
        for fname, jkey, value in zip(WORKING_DATA_FIELDS, WORKING_DATA_JSON_KEYS, cells):
            if fname in _BOOL_FIELDS:
                record[jkey] = value.strip().lower() in _TRUE_CELLS
            else:
                record[jkey] = "" if value == EMPTY_CELL else value
        records.append(record)

    if header_cells is None:
        raise ValueError("no markdown table found")
    return records


def rows_from_markdown(markdown: str) -> list:
    """Markdown table -> ``WorkingDataRow`` objects (metadata is not recoverable)."""
    return [WorkingDataRow.from_json_dict(rec) for rec in parse_markdown_table(markdown)]


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------


def write_markdown(rows: Sequence[WorkingDataRow], path: Path, *, sort: bool = True) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render_markdown_table(rows, sort=sort))
    return path


def export_json(rows: Sequence[WorkingDataRow], path: Path, *, sort: bool = True) -> Path:
    """Write the section-4 JSON array straight from rows."""
    ordered = sort_rows(rows) if sort else list(rows)
    payload = [r.to_json_dict() for r in ordered]
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    return path


def export_json_from_markdown(markdown_path: Path, json_path: Path) -> Path:
    """Section-5 path: parse the emitted markdown table, then write the JSON array."""
    with open(markdown_path, "r", encoding="utf-8") as fh:
        markdown = fh.read()
    payload = parse_markdown_table(markdown)
    json_path = Path(json_path)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    with open(json_path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    return json_path
